services:
  db:
    image: postgres:18
    container_name: go-pedidos-api
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_pedidos
    ports:
      - "5433:5432"
    volumes:
      - api-pedidos-data:/var/lib/postgresql

volumes:
  api-pedidos-data: